angelnews/angelnews/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
   ]

angelnews/blog/urls.py
from django.urls import path


from . import views

app_name = "blog"

urlpatterns = [
	path('', views.listar_noticias, name="listar_noticias"),
	path("<int:id_noticia>/", views.ver_noticia,  name="ver_noticia")
]

angelnews/blog/models.py
from django.db import models

class Noticia(models.Model):
	titulo = models.CharField(max_length=200)
	descripcion = models.CharField(max_length=1000)
	fecha_pub = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "%s %s" % (self.titulo,self.fecha_pub)

angelnews/blog/forms.py
from django import forms


from .models import *


class NuevaNoticiaForm(forms.Form):
	titulo = forms.CharField(label="Titulo")
	descripcion = forms.CharField(label="Descripcion")

angelnews/blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse

#MVT
#Model
#View
#Template
#Importaciones de Librerias Personales
from . import models
from . import forms

def listar_noticias(request):
	"""
		obtiene las noticias de la base de datos

		Retorna:
			El listado de las noticias
	"""
	#Obtiene el listado de todas las noticias
	#De la base de datos y la asigna a la variable
	#noticias
	noticias = models.Noticia.objects.all()

	#Retorna todo renderizado para ser leido en el
	#explorador, tiene tres parametros
	#Solicitud(request), palntilla de datos y datos
	return render(
					request, 
					'./noticias/index.html',
					 {'news':noticias}
				)


def ver_noticia(resquest, id_noticia):
	"""
		obtiene una noticia de la base de datos 

		parametros:
		id_noticia es numerico y hace referencia 
		al indetificador  de la noticias buscada 

		retorna 
			la noticia buscada  si existe
	"""

	noticia = models.Noticia.objects.get(id=id_noticia)

	return render (
					resquest,
						"./noticias/detalle.html",
						{"noticia":noticia}
					)



def agregar_noticias(resquest):
	"""
		Agrega una nueva noticia a la base de datos 

		Retorna
				al sitio principal de noticia
	"""

	if resquest.method == "post":
		#crea un formularionuevo con el metodo post
		form = forms.NuevaNoticiaForm(resquest.POST)

		if forms.is_valid():
			#si el formulario es valido se procede con el proceso 
			#de agregar el nuevo registro a la base de datos
			noticia = models.Noticia()
			noticia.titulo = forms.cleaned_data['titulo']
			noticia.descripcion = form.cleaned_data['descripcion']
			noticia.save()

			#Redireacciona a la pagina principal
			return HttpResponseRedirect(
							render(
									'blog:listar_noticias'
									)
							)
		else:
			return HttpResponse("Formulario invalido")
		#si el metodo de petecion no es agregar
		#se carga el formulario desde cero
		else:
			forms.NuevaNoticiaForm()

		return render (resquest, './noticias/agregar.html', {'form':form})

angelnews/blog/templates/noticias/detalle.html
<!--Extiende la configuracion y maquetacion de la pagina base-->
{% extends 'base.html' %}


{% block titulo %}
	{{ noticia.titulo }}
{% endblock %}


<!--
	Pasa la informacion que va a ser mostrada en el bloque
	informacion de la pagina base.html
-->
{% block informacion %}

	<h1>{{ noticia.titulo }}</h1>

	<p>{{ noticia.descripcion }}</p>
	<div class="text-secondary">
		 Publicacion: {{ noticia.fecha_pub }}
	</div>
{% endblock %}

angelnews/blog/templates/noticias/index.html
<!--Extiende la configuracion y maquetacion de la pagina base-->
{% extends 'base.html' %}

<!--
	Pasa la informacion que va a ser mostrada en el bloque
	informacion de la pagina base.html
-->
{% block informacion %}
	{% for new in news %}
		<div class="p-1">
			<h2 class="text-primary">
				<a href="{% url 'blog:ver_noticia' new.id %}">
					{{ new.titulo }}
				</a>
			</h2>
			<p>
				{{ new.descripcion }}
				<a href="{% url 'blog:ver_noticia' new.id %}">
					ver...
			</a>
		</p>
		<hr>
	</div >		
	{% endfor %}
{% endblock %}